# Generated by Django 4.2.5 on 2023-09-07 05:24

from django.db import migrations, models
import django_extensions.db.fields
import lazermig_.utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to=lazermig_.utils.image_upload_to, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug'),
        ),
    ]
