# Generated by Django 4.2.5 on 2023-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newstag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
